name: Feature branch deployment

on:
  push:
    branches-ignore: [ master, staging ]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:

    # Checkout code including submodule
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPOSITORY_READ_TOKEN }}
        submodules: true

    # Install node
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Build
#    - name: Build
#      run: |
#        cd app/
#        npm install
#        npm run build

    # Inject SH Config file
    - name: replace instance ID
      uses: datamonsters/replace-action@v2
      with:
        files: 'app/dist/shConfig.js'
        replacements: '$SH_INSTANCE_ID=${{ secrets.SH_INSTANCE_ID }}'


    - name: Print GitHub context
      run: |
        echo ${{ github.ref }}
        echo ${GITHUB_REF##*/}
